Ci/add snap ci
ubuntu-robotics/ros-foxglove-bridge pull request #4
Opened 2024-04-05 09:22 UTC by Guillaumebeuzeboc

2024-04-05 10:01 UTC, Guillaumebeuzeboc commented
Secret has been added.

2024-04-08 08:17 UTC, giusebar requested changes

2024-04-08 08:17 UTC, giusebar commented on .github/workflows/monthly.yaml
> +    uses: canonical/ros-foxglove-bridge/.github/workflows/snap.yaml@main
replace canonical with ubuntu-robotics

2024-04-08 08:17 UTC, giusebar commented on .github/workflows/snap.yaml
> +      - feature/snap
I see there is an old PR not merged from jeremie, do we keep the snap on feature/snap or should we merge everything to main?

2024-04-08 09:48 UTC, Guillaumebeuzeboc commented on .github/workflows/snap.yaml
> +      - feature/snap
They never replied about the snapping of the agent. I think if we want to keep it, we will simply have a standalone repository just for the snap.

2024-04-08 13:01 UTC, giusebar approved these changes

2024-04-08 13:23 UTC, merged